# Generated by Django 5.1.5 on 2025-02-01 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 18, 50, 47, 874585, tzinfo=datetime.timezone.utc)),
        ),
    ]
