# Generated by Django 5.1.5 on 2025-02-01 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoApp', '0002_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 19, 30, 42, 413556, tzinfo=datetime.timezone.utc)),
        ),
    ]
