# Generated by Django 5.1.5 on 2025-02-03 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoApp', '0003_alter_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 18, 15, 34, 230370, tzinfo=datetime.timezone.utc)),
        ),
    ]
